export const PATIENT_HISTORY_LIST_BEGIN = 'PATIENT_HISTORY_LIST_BEGIN';
export const PATIENT_HISTORY_LIST_SUCCESS = 'PATIENT_HISTORY_LIST_SUCCESS';
export const PATIENT_HISTORY_LIST_FAIL = 'PATIENT_HISTORY_LIST_FAIL';

export const PATIENT_HISTORY_CREATE_BEGIN = 'PATIENT_HISTORY_CREATE_BEGIN';
export const PATIENT_HISTORY_CREATE_SUCCESS = 'PATIENT_HISTORY_CREATE_SUCCESS';
export const PATIENT_HISTORY_CREATE_FAIL = 'PATIENT_HISTORY_CREATE_FAIL';

export const PATIENT_HISTORY_DELETE_BEGIN = 'PATIENT_HISTORY_DELETE_BEGIN';
export const PATIENT_HISTORY_DELETE_SUCCESS = 'PATIENT_HISTORY_DELETE_SUCCESS';
export const PATIENT_HISTORY_DELETE_FAIL = 'PATIENT_HISTORY_DELETE_FAIL';

export const PATIENT_HISTORY_RESET_HISTORY_TYPE = 'PATIENT_HISTORY_RESET_HISTORY_TYPE';