# Generated by Django 3.0.7 on 2020-07-14 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_patient_id',
            field=models.PositiveIntegerField(default=0, max_length=6),
        ),
    ]
