# Generated by Django 3.0.7 on 2020-07-14 18:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0002_auto_20200714_2331'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_patient_id',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(999999)]),
        ),
    ]
