# Generated by Django 3.0.7 on 2020-07-14 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0003_auto_20200714_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='last_patient_id',
            field=models.CharField(default='000000', max_length=6),
        ),
    ]
