# Generated by Django 3.0.7 on 2020-07-30 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0005_auto_20200725_1707'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='userprofile',
        ),
    ]
