# Generated by Django 3.0.7 on 2020-07-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('misc', '0006_auto_20200730_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'hospitals_hospital',
            },
        ),
        migrations.CreateModel(
            name='ProfessionalService',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professional_service', models.CharField(max_length=100)),
            ],
        ),
    ]
