# Generated by Django 3.0.7 on 2020-07-12 13:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='patient_id',
            field=models.CharField(max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('user', 'patient_id')},
        ),
    ]
