# Generated by Django 3.0.7 on 2020-07-14 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20200714_1809'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patient',
            old_name='ud_patient_id',
            new_name='patient_id',
        ),
    ]
