# Generated by Django 3.0.7 on 2020-07-14 17:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('patients', '0003_auto_20200714_2231'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='patient',
            unique_together={('user', 'patient_id')},
        ),
    ]
