# Generated by Django 3.0.7 on 2020-06-26 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20200625_2000'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patientfamilyhistory',
            old_name='history_name',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='patientobgynhistory',
            old_name='history_name',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='patientpasthistory',
            old_name='history_name',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='patientpersonalhistory',
            old_name='history_name',
            new_name='history',
        ),
        migrations.RenameField(
            model_name='patientpresenthistory',
            old_name='history_name',
            new_name='history',
        ),
    ]
