# Generated by Django 3.0.7 on 2020-06-28 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0006_auto_20200626_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='last_consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='last_consultation_for_patient', to='consultations.Consultation'),
        ),
    ]
