from .basic_data import PatientMobileSerializer, PatientEmailSerializer, PatientSearchSerializer, \
	PatientBasicCreateSerializer, PatientBasicRetrieveUpdateSerializer
from .history_data import PatientFamilyHistorySerializer, PatientOBGYNHistorySerializer, \
	PatientPastHistorySerializer, PatientPersonalHistorySerializer, PatientPresentHistorySerializer
