# Generated by Django 3.0.7 on 2020-07-13 09:01

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import abstract.fields.fields


class Migration(migrations.Migration):
	initial = True

	dependencies = [
	]

	operations = [
		migrations.CreateModel(
			name='Doctor',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('building_details', models.CharField(blank=True, max_length=50, null=True)),
				('lane', models.CharField(blank=True, max_length=50, null=True)),
				('area', models.CharField(blank=True, max_length=50, null=True)),
				('city', models.CharField(blank=True, default='Mumbai', max_length=50, null=True)),
				('pincode', models.CharField(blank=True, max_length=6, null=True,
				                             validators=[django.core.validators.MinLengthValidator(6)])),
				('title', models.CharField(
					choices=[('Dr', 'Dr.'), ('Mr', 'Mr.'), ('Mas', 'Master'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.')],
					max_length=3)),
				('name', models.CharField(max_length=100)),
				('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
				('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown')], default='U',
				                            max_length=1)),
				('qualification', models.CharField(blank=True, max_length=50, null=True)),
				('designation', models.CharField(blank=True, max_length=50, null=True)),
			],
			options={
				'abstract': False,
			},
		),
		migrations.CreateModel(
			name='DoctorMobile',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('mobile', abstract.fields.fields.MobileField(max_length=11)),
				('synced_with_contacts',
				 models.BooleanField(default=False, verbose_name='Is the mobile number synced with Google Contacts?')),
				('hide_from_user', models.BooleanField(default=False,
				                                       verbose_name='Do you want the program to ignore syncing this mobile number?')),
				('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles',
				                             to='doctors.Doctor')),
			],
			options={
				'verbose_name': 'Doctor (Mobile)',
				'verbose_name_plural': 'Doctor (Mobiles)',
				'unique_together': {('doctor', 'mobile')},
			},
		),
		migrations.CreateModel(
			name='DoctorEmail',
			fields=[
				('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
				('email', models.EmailField(max_length=100)),
				('synced_with_contacts',
				 models.BooleanField(default=False, verbose_name='Is the email synced with Google Contacts?')),
				('hide_from_user', models.BooleanField(default=False,
				                                       verbose_name='Do you want the program to ignore syncing this email?')),
				('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails',
				                             to='doctors.Doctor')),
			],
			options={
				'verbose_name': 'Doctor (Email)',
				'verbose_name_plural': 'Doctor (Emails)',
				'unique_together': {('doctor', 'email')},
			},
		),
	]
