# Generated by Django 3.0.7 on 2020-06-23 19:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('Dr', 'Dr.'), ('Mr', 'Mr.'), ('Master', 'Master'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.')], max_length=6)),
                ('name', models.CharField(max_length=100)),
                ('dob', models.DateField(blank=True, null=True, verbose_name='Date of Birth')),
                ('building_details', models.CharField(blank=True, max_length=50, null=True)),
                ('lane', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='Mumbai', max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DoctorMobile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mobile', models.CharField(max_length=10)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
            options={
                'verbose_name': 'Doctor (Mobile)',
                'verbose_name_plural': 'Doctor (Mobiles)',
                'unique_together': {('doctor', 'mobile')},
            },
        ),
    ]
