# Generated by Django 3.0.7 on 2020-07-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('Dr', 'Dr.'), ('Mr', 'Mr.'), ('Mas', 'Master'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.')], max_length=5),
        ),
    ]
