# Generated by Django 3.0.7 on 2020-06-24 15:41

import abstract.fields.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormobile',
            name='hide_from_user',
            field=models.BooleanField(default=False, help_text='User chooses to ignore syncing particular mobile number with Google Contacts', verbose_name='Do you want the program to ignore syncing this mobile number?'),
        ),
        migrations.AddField(
            model_name='doctormobile',
            name='synced_with_contacts',
            field=models.BooleanField(default=False, help_text='Is the particular mobile number synced with Google Contacts', verbose_name='Is the mobile number synced with Google Contacts?'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='title',
            field=models.CharField(choices=[('Dr', 'Dr.'), ('Mr', 'Mr.'), ('Mas', 'Master'), ('Mrs', 'Mrs.'), ('Ms', 'Ms.')], max_length=3),
        ),
        migrations.AlterField(
            model_name='doctormobile',
            name='mobile',
            field=abstract.fields.fields.MobileField(max_length=11),
        ),
        migrations.CreateModel(
            name='DoctorEmail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('synced_with_contacts', models.BooleanField(default=False, help_text='Is the particular email synced with Google Contacts', verbose_name='Is the email synced with Google Contacts?')),
                ('hide_from_user', models.BooleanField(default=False, help_text='User chooses to ignore syncing particular email with Google Contacts', verbose_name='Do you want the program to ignore syncing this email?')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='doctors.Doctor')),
            ],
            options={
                'verbose_name': 'Doctor (Email)',
                'verbose_name_plural': 'Doctor (Emails)',
                'unique_together': {('doctor', 'email')},
            },
        ),
    ]
