# Generated by Django 3.0.7 on 2020-06-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0002_auto_20200624_2111'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoremail',
            name='hide_from_user',
            field=models.BooleanField(default=False, help_text='User chooses to ignore syncing particular email with Google Contacts'),
        ),
        migrations.AlterField(
            model_name='doctoremail',
            name='synced_with_contacts',
            field=models.BooleanField(default=False, help_text='Is the particular email synced with Google Contacts'),
        ),
    ]
