# Generated by Django 3.0.7 on 2020-06-25 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0004_auto_20200624_2128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctoremail',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='doctors.Doctor'),
        ),
        migrations.AlterField(
            model_name='doctormobile',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mobiles', to='doctors.Doctor'),
        ),
    ]
