# Generated by Django 3.0.7 on 2020-07-14 12:29

import abstract.fields.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('doctors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultation_date', models.DateField(default=django.utils.timezone.now)),
                ('prescription_printed', models.BooleanField(verbose_name='Prescription to be printed? (as opposed to a digital copy)')),
            ],
        ),
        migrations.CreateModel(
            name='DrugMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('formulation', models.CharField(choices=[('Tab', 'Tablet'), ('Cap', 'Capsule'), ('Syr', 'Syrup'), ('Oin', 'Ointment'), ('Inj', 'Injection')], max_length=3)),
                ('brand_name', models.CharField(max_length=100)),
                ('generic_name', models.CharField(max_length=500)),
                ('strength', models.CharField(max_length=50)),
                ('route', models.CharField(max_length=50)),
                ('dosage_default', models.CharField(blank=True, max_length=20, null=True)),
                ('meal_relation_default', models.CharField(blank=True, max_length=50, null=True)),
                ('disabled', models.BooleanField(default=False)),
                ('company_name', models.CharField(blank=True, max_length=100, null=True)),
                ('company_division', models.CharField(blank=True, max_length=100, null=True)),
                ('group_number', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('number_of_times_prescribed', models.PositiveIntegerField(default=0)),
                ('priority_in_group', abstract.fields.fields.PercentageField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Drug Master',
                'verbose_name_plural': 'Drugs Master',
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='follow_up', serialize=False, to='consultations.Consultation')),
                ('follow_up_after', models.CharField(max_length=50, verbose_name='Follow Up')),
            ],
            options={
                'verbose_name': 'Follow Up',
                'verbose_name_plural': 'Follow Up',
            },
        ),
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('consultation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='remarks', serialize=False, to='consultations.Consultation')),
                ('remark', models.TextField(max_length=300)),
            ],
            options={
                'verbose_name': 'Remark',
                'verbose_name_plural': 'Remarks',
            },
        ),
        migrations.CreateModel(
            name='ReferredTo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_details', models.CharField(blank=True, max_length=50, null=True)),
                ('lane', models.CharField(blank=True, max_length=50, null=True)),
                ('area', models.CharField(blank=True, max_length=50, null=True)),
                ('city', models.CharField(blank=True, default='Mumbai', max_length=50, null=True)),
                ('pincode', models.CharField(blank=True, max_length=6, null=True, validators=[django.core.validators.MinLengthValidator(6)])),
                ('doctor_name', models.CharField(max_length=100)),
                ('doctor_qualification', models.CharField(blank=True, max_length=50, null=True)),
                ('doctor_mobile', abstract.fields.fields.MobileField(max_length=11)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_to', to='consultations.Consultation')),
            ],
            options={
                'verbose_name': 'Referred To',
                'verbose_name_plural': 'Referred To',
            },
        ),
        migrations.CreateModel(
            name='ReferredFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_cut', abstract.fields.fields.PercentageField(default=0)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_from', to='consultations.Consultation')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_referred', to='doctors.Doctor')),
            ],
            options={
                'verbose_name': 'Referred From',
                'verbose_name_plural': 'Referred From',
            },
        ),
        migrations.CreateModel(
            name='InvestigationPrescribed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.CharField(max_length=50)),
                ('when_to_do', models.CharField(blank=True, max_length=50, null=True)),
                ('where_to_do', models.CharField(blank=True, max_length=50, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations_prescribed', to='consultations.Consultation')),
            ],
            options={
                'verbose_name': 'Investigation Prescribed',
                'verbose_name_plural': 'Investigations Prescribed',
            },
        ),
        migrations.CreateModel(
            name='InvestigationGroups',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.CharField(max_length=50)),
                ('group_name', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Investigation Group',
            },
        ),
        migrations.CreateModel(
            name='InvestigationDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('investigation', models.CharField(max_length=50)),
                ('date_done', models.DateField(blank=True, null=True)),
                ('investigation_result', models.CharField(max_length=50)),
                ('hide_from_chart', models.BooleanField(default=False)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='investigations_done', to='consultations.Consultation')),
            ],
            options={
                'verbose_name': 'Investigation Done',
                'verbose_name_plural': 'Investigations Done',
            },
        ),
        migrations.CreateModel(
            name='GeneralAdvice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('advice', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='general_advice', to='consultations.Consultation')),
            ],
            options={
                'verbose_name': 'General Advice',
                'verbose_name_plural': 'General Advice',
            },
        ),
        migrations.CreateModel(
            name='ExaminationMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_heading', models.CharField(max_length=50)),
                ('examination', models.CharField(max_length=50)),
                ('enable_basic_data_field', models.BooleanField()),
                ('enable_reading_field', models.BooleanField()),
                ('units', models.CharField(blank=True, max_length=10, null=True)),
                ('enable_description_field', models.BooleanField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Examination Master',
                'verbose_name_plural': 'Examinations Master',
            },
        ),
        migrations.CreateModel(
            name='ExaminationDone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examination_heading', models.CharField(max_length=50)),
                ('examination', models.CharField(max_length=50)),
                ('basic_info', models.CharField(blank=True, max_length=50, null=True)),
                ('reading', models.CharField(blank=True, max_length=50, null=True)),
                ('units', models.CharField(blank=True, max_length=10, null=True)),
                ('description', models.TextField(blank=True, max_length=150, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examination', to='consultations.Consultation')),
            ],
            options={
                'verbose_name': 'Examination Done',
                'verbose_name_plural': 'Examinations Done',
            },
        ),
        migrations.CreateModel(
            name='DrugPrescribed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(blank=True, max_length=20, null=True)),
                ('meal_relation', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=100, null=True)),
                ('remarks', models.TextField(blank=True, max_length=150, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drugs_prescribed', to='consultations.Consultation')),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='consultations.DrugMaster')),
            ],
            options={
                'verbose_name': 'Drug Prescribed',
                'verbose_name_plural': 'Drugs Prescribed',
            },
        ),
        migrations.CreateModel(
            name='Diagnosis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.CharField(max_length=100)),
                ('as_of', models.CharField(blank=True, default='As of 14-Jul-2020', max_length=100, null=True)),
                ('description', models.TextField(blank=True, max_length=500, null=True)),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnosis', to='consultations.Consultation')),
            ],
            options={
                'verbose_name_plural': 'Diagnoses',
            },
        ),
    ]
