# Generated by Django 3.0.7 on 2020-07-14 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('consultations', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations', to='patients.Patient'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='referredto',
            unique_together={('consultation', 'doctor_name', 'doctor_qualification')},
        ),
        migrations.AlterUniqueTogether(
            name='referredfrom',
            unique_together={('consultation', 'doctor_id')},
        ),
        migrations.AlterUniqueTogether(
            name='generaladvice',
            unique_together={('consultation', 'advice')},
        ),
        migrations.AlterUniqueTogether(
            name='examinationmaster',
            unique_together={('examination_heading', 'examination')},
        ),
        migrations.AlterUniqueTogether(
            name='examinationdone',
            unique_together={('consultation', 'examination_heading', 'examination')},
        ),
        migrations.AlterUniqueTogether(
            name='drugprescribed',
            unique_together={('consultation', 'drug')},
        ),
        migrations.AlterUniqueTogether(
            name='drugmaster',
            unique_together={('formulation', 'brand_name', 'generic_name', 'strength', 'route')},
        ),
        migrations.AlterUniqueTogether(
            name='diagnosis',
            unique_together={('consultation', 'diagnosis')},
        ),
    ]
