# Generated by Django 3.0.7 on 2020-06-29 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='as_of',
            field=models.CharField(blank=True, default='As of 29-Jun-2020', max_length=100, null=True),
        ),
    ]
