# Generated by Django 3.0.7 on 2020-07-13 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
	initial = True

	dependencies = [
		('patients', '0001_initial'),
		('consultations', '0001_initial'),
	]

	operations = [
		migrations.AddField(
			model_name='consultation',
			name='patient',
			field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='consultations',
			                        to='patients.Patient'),
		),
		migrations.AlterUniqueTogether(
			name='referredto',
			unique_together={('consultation', 'doctor_name', 'doctor_qualification')},
		),
		migrations.AlterUniqueTogether(
			name='referredfrom',
			unique_together={('consultation', 'doctor_id')},
		),
		migrations.AlterUniqueTogether(
			name='generaladvice',
			unique_together={('consultation', 'advice')},
		),
		migrations.AlterUniqueTogether(
			name='examinationdone',
			unique_together={('consultation', 'examination_heading', 'examination')},
		),
		migrations.AlterUniqueTogether(
			name='drugprescribed',
			unique_together={('consultation', 'drug')},
		),
		migrations.AlterUniqueTogether(
			name='diagnosis',
			unique_together={('consultation', 'diagnosis')},
		),
	]
