# Generated by Django 3.0.7 on 2020-07-13 13:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
	dependencies = [
		migrations.swappable_dependency(settings.AUTH_USER_MODEL),
		('consultations', '0002_auto_20200713_1431'),
	]

	operations = [
		migrations.AddField(
			model_name='consultation',
			name='user',
			field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
			                        to=settings.AUTH_USER_MODEL),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='drugmaster',
			name='user',
			field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
			                        to=settings.AUTH_USER_MODEL),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='examinationmaster',
			name='user',
			field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
			                        to=settings.AUTH_USER_MODEL),
			preserve_default=False,
		),
		migrations.AddField(
			model_name='investigationgroups',
			name='user',
			field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE,
			                        to=settings.AUTH_USER_MODEL),
			preserve_default=False,
		),
		migrations.AlterField(
			model_name='investigationgroups',
			name='group_name',
			field=models.CharField(blank=True, max_length=50, null=True),
		),
	]
