# Generated by Django 3.0.7 on 2020-07-03 14:23

import abstract.fields.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_auto_20200625_2000'),
        ('consultations', '0002_auto_20200703_1935'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferredFrom',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('percentage_cut', abstract.fields.fields.PercentageField()),
                ('consultation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referred_from', to='consultations.Consultation')),
                ('doctor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultations_referred', to='doctors.Doctor')),
            ],
            options={
                'verbose_name': 'Referred From',
                'verbose_name_plural': 'Referred From',
            },
        ),
    ]
