# Generated by Django 3.0.7 on 2020-07-03 15:32

import abstract.fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('doctors', '0007_auto_20200625_2000'),
        ('consultations', '0003_referredfrom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referredfrom',
            name='percentage_cut',
            field=abstract.fields.fields.PercentageField(default=0),
        ),
        migrations.AlterUniqueTogether(
            name='referredfrom',
            unique_together={('consultation', 'doctor_id')},
        ),
    ]
