# Generated by Django 3.0.7 on 2020-07-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_auto_20200730_1831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationdone',
            name='reading',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
