# Generated by Django 3.0.7 on 2020-07-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0004_auto_20200703_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='diagnosis',
            name='as_of',
            field=models.CharField(blank=True, default='As of 05-Jul-2020', max_length=100, null=True),
        ),
    ]
