# Generated by Django 3.0.7 on 2020-07-30 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0005_auto_20200730_1848'),
    ]

    operations = [
        migrations.AlterField(
            model_name='examinationdone',
            name='reading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
