export const PATIENT_BEGIN = 'PATIENT_BEGIN';
export const PATIENT_SUCCESS = 'PATIENT_SUCCESS';
export const PATIENT_FAIL = 'PATIENT_FAIL';
export const PATIENT_NEW_PATIENT = 'PATIENT_NEW_PATIENT';
export const PATIENT_EXISTING_PATIENT = 'PATIENT_EXISTING_PATIENT';