export const PATIENT_RESET_STATE = 'PATIENT_RESET_STATE';

export const PATIENT_SET_PATIENT_ID_TYPE = 'PATIENT_SET_PATIENT_ID_TYPE';
export const PATIENT_SET_PATIENT_ID_DISABLED = 'PATIENT_SET_PATIENT_ID_DISABLED';

export const PATIENT_ADD_NEW_BEGIN = 'PATIENT_ADD_NEW_BEGIN';
export const PATIENT_ADD_NEW_SUCCESS = 'PATIENT_ADD_NEW_SUCCESS';
export const PATIENT_ADD_NEW_FAIL = 'PATIENT_ADD_NEW_FAIL';

export const PATIENT_RETRIEVE_BEGIN = 'PATIENT_RETRIEVE_BEGIN';
export const PATIENT_RETRIEVE_SUCCESS = 'PATIENT_RETRIEVE_SUCCESS';
export const PATIENT_RETRIEVE_FAIL = 'PATIENT_RETRIEVE_FAIL';

export const PATIENT_SEARCH_BEGIN = 'PATIENT_SEARCH_BEGIN';
export const PATIENT_SEARCH_SUCCESS = 'PATIENT_SEARCH_SUCCESS';
export const PATIENT_SEARCH_FAIL = 'PATIENT_SEARCH_FAIL';
export const PATIENT_SEARCH_SET_DROPDOWN_VISIBILITY = 'PATIENT_SEARCH_SET_DROPDOWN_VISIBILITY';

export const PATIENT_UPDATE_BEGIN = 'PATIENT_UPDATE_BEGIN';
export const PATIENT_UPDATE_SUCCESS = 'PATIENT_UPDATE_SUCCESS';
export const PATIENT_UPDATE_FAIL = 'PATIENT_UPDATE_FAIL';