export const PATIENT_BASIC_RESET_STATE = 'PATIENT_BASIC_RESET_STATE';

export const PATIENT_SET_PATIENT_ID_TYPE = 'PATIENT_BASIC_SET_PATIENT_ID_TYPE';
export const PATIENT_SET_PATIENT_ID_DISABLED = 'PATIENT_BASIC_SET_PATIENT_ID_DISABLED';

export const PATIENT_BASIC_SET_FORM_DATA = 'PATIENT_BASIC_SET_FORM_DATA';
export const PATIENT_BASIC_RESET_FORM_DATA = 'PATIENT_BASIC_RESET_FORM_DATA';

export const PATIENT_ADD_NEW_BEGIN = 'PATIENT_BASIC_ADD_NEW_BEGIN';
export const PATIENT_ADD_NEW_SUCCESS = 'PATIENT_BASIC_ADD_NEW_SUCCESS';
export const PATIENT_ADD_NEW_FAIL = 'PATIENT_BASIC_ADD_NEW_FAIL';

export const PATIENT_BASIC_RETRIEVE_BEGIN = 'PATIENT_BASIC_RETRIEVE_BEGIN';
export const PATIENT_BASIC_RETRIEVE_SUCCESS = 'PATIENT_BASIC_RETRIEVE_SUCCESS';
export const PATIENT_BASIC_RETRIEVE_FAIL = 'PATIENT_BASIC_RETRIEVE_FAIL';

export const PATIENT_SEARCH_BEGIN = 'PATIENT_BASIC_SEARCH_BEGIN';
export const PATIENT_SEARCH_SUCCESS = 'PATIENT_BASIC_SEARCH_SUCCESS';
export const PATIENT_SEARCH_FAIL = 'PATIENT_BASIC_SEARCH_FAIL';
export const PATIENT_SEARCH_SET_DROPDOWN_VISIBILITY = 'PATIENT_BASIC_SEARCH_SET_DROPDOWN_VISIBILITY';

export const PATIENT_BASIC_UPDATE_BEGIN = 'PATIENT_BASIC_UPDATE_BEGIN';
export const PATIENT_BASIC_UPDATE_SUCCESS = 'PATIENT_BASIC_UPDATE_SUCCESS';
export const PATIENT_BASIC_UPDATE_FAIL = 'PATIENT_BASIC_UPDATE_FAIL';